[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 10000000
fs_permissions = [{ access = "read-write", path = "./release/"}]
solc_version = "0.8.28"

additional_compiler_profiles = [ 
	{ name = "general", via_ir = true, optimizer_runs = 1000000 },
	{ name = "computepool", via_ir = true, optimizer_runs = 100 },
]


# enforce compiling tests without via_ir and only some heavy contract with via_ir
# note: it will only work if tests are using vm.deployCode to deploy contract
compilation_restrictions = [
    { paths = "src/ComputePool.sol", via_ir = true, optimizer_runs = 100},
    { paths = "test/**", via_ir = true},
    { paths = "src/**", via_ir = true },
    { paths = "script/**", via_ir = true},
]

[rpc_endpoints]
local = "http://127.0.0.1:8545"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
